version: '3.8'
services:
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
#      - ./config/tempo-data:/tmp/tempo
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_INSTALL_PLUGINS=grafana-service-graph-datasource,pyroscope-datasource
    volumes:
      # set up datasource khi grafana dc khoi tao
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - spring-network

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    environment:
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    ports:
      - "8082:8082"
    depends_on:
      - tempo

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - ./config/pyroscope:/etc/pyroscope.yaml
    command: [ "server" ]

  order-service:
    image: order-service:latest
    container_name: order-service
    environment:
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar -javaagent:/app/pyroscope.jar"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      PYROSCOPE_APPLICATION_NAME: order-service
      PAYMENT_SERVICE_URL: http://payment-service:8082
    ports:
      - "8084:8084"
    depends_on:
      - payment-service
      - tempo
    networks:
      - spring-network

volumes:
  grafana-storage:
  pyroscope-storage:
  postgres_data:

networks:
  spring-network: