version: '3.8'
services:
  payment-service:
    image: payment-service:latest
    environment:
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: /logs
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: aces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: /v1/metrics
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_METRICS_HEADERS: ""
      OTEL_EXPORTER_OTLP_TRACES_HEADERS: ""
      OTEL_EXPORTER_OTLP_LOGS_HEADERS: ""
    ports:
      - "8082:8082"

  order-service:
    image: order-service:latest
    environment:
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: /logs
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: aces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: /v1/metrics
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_METRICS_HEADERS: ""
      OTEL_EXPORTER_OTLP_TRACES_HEADERS: ""
      OTEL_EXPORTER_OTLP_LOGS_HEADERS: ""
      PAYMENT_SERVICE_URL: http://payment-service:8082
    ports:
      - "8084:8084"
    depends_on:
      - payment-service